version: '3'
services:
  alluxio-master:
    image: alluxio/alluxio:latest
    environment:
      - ALLUXIO_JAVA_OPTS=-Dalluxio.master.hostname=alluxio-master -Dalluxio.master.mount.table.root.ufs=wasb://data01@stgtaxidataset.blob.core.windows.net/  -Dfs.azure.secure.mode=true -Dfs.azure.account.key.stgtaxidataset.blob.core.windows.net="YqbOr743v9ouXg/AyumlVfk+lKyaQv8wbs+bl6JkkAtEYUz6BYMEDpT31Eb2qvdnV/DlizQZ1+Y0+ASt/W759g==" 
    command: master
    ports:
      - 19999:19999 # Alluxio Web UI
    networks:
      - alluxio_net

  alluxio-worker1:
    image: alluxio/alluxio:latest
    environment:
      - ALLUXIO_JAVA_OPTS=-Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master
    command: worker
    networks:
      - alluxio_net

  alluxio-worker2:
    image: alluxio/alluxio:latest
    environment:
      - ALLUXIO_JAVA_OPTS=-Dalluxio.worker.memory.size=1G -Dalluxio.master.hostname=alluxio-master
    command: worker
    networks:
      - alluxio_net

networks:
  alluxio_net:
