version: '3'
services:
  trino:
    image: trinodb/trino
    ports:
      - "8080:8080"
    environment:
      - TRINO_CATALOGS=/etc/trino/catalog
      - TRINO_ETC=/etc/trino
    volumes:
      - ./catalog:/etc/trino/catalog
      - ./etc:/etc/trino/etc

  db:
    image: postgres
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=testdb
    ports:
      - "5432:5432"
